name: shelf_backend
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.2
  mysql1: ^0.20.0
  dotenv: ^4.2.0
  crypto: ^3.0.7
  dart_jsonwebtoken: ^3.3.1
  get_it: ^9.2.0

dev_dependencies:
  http: ^1.2.2
  lints: ^6.0.0
  test: ^1.25.6
